name: update wijgaanappie op server

on: 
  push:
    branches: [master, mobile]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: wijgaanappie.nl
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 7685
        script: ./download.sh
